### ISSUE TITLE
--js flag seems to be broken

### ISSUE THREAD

**Issue by am97** [coderaiser/minify#60] opened 2020-10-29 00:43 UTC
Hello,

Since minify v5.2.0, the `--js` flag seems to no longer work. For example:

```bash
$ cat << EOT > hello.js
const hello = 'world';

for (let i = 0; i < hello.length; i++) {
    console.log(hello[i]);
}
EOT
$ cat hello.js | minify --js
Promise { <pending> }
```

With minify v5.1.1 I get the expected result:

```bash
$ cat hello.js | minify --js
const hello="world";for(let l=0;l<hello.length;l++)console.log(hello[l]);
```

A workaround for minify v5.2.0 and v6.0.0 is to not use the `--js` flag

```bash
$ minify hello.js 
const hello="world";for(let l=0;l<hello.length;l++)console.log(hello[l]);
```

**Comment by coderaiser** [comment] 2020-10-29 15:24
Thank you :), fixed with ba496f3, landed in [v6.0.1](https://github.com/coderaiser/minify/releases/tag/v6.0.1) 🎉 .
Is it works for you?

**Comment by am97** [comment] 2020-11-01 21:20
Yes, it is working now, thank you !

**Comment by coderaiser** [comment] 2024-07-02 17:05
@vitek-dev how it works for you?

**Comment by coderaiser** [comment] 2024-07-02 20:31
I cannot reproduce this:

```sh
coderaiser@localcmd:~/minify$ echo 'if (a) alert()' | minify --js
a&&alert();
```

**Closed by coderaiser** 2024-07-02 20:31 UTC
Labels: bug
