### ISSUE TITLE
Error with latest minify version

### ISSUE THREAD

**Issue by matteociasco** [coderaiser/minify#87] opened 2021-10-04 09:46 UTC
Hi everyone, when i try to run the following code from an .sh script:

```bash
for FILE in $(find $1 -name *.css)
do
  if [[ $FILE != *.min.css ]] && [[ $FILE == *.css ]]; then
    minify $FILE > ${FILE/.css/".min.css"}
  fi
done
```

I get the following error:

`Directory import '/usr/local/lib/node_modules/minify/' is not supported resolving ES modules imported from /usr/local/lib/node_modules/minify/bin/minify.js`

The npm package is installed like this:
`npm install -g minify`

### Enviroment
- node **14**
- runs on **bitbucket pipeline**

**Comment by coderaiser** [comment] 2021-10-04 13:07
It’s a duplicate of https://github.com/coderaiser/minify/issues/86. Just re-install `minify`, it’s already fixed.
Is it works for you?

**Closed by coderaiser** 2021-10-04 13:07 UTC
Labels: bug, duplicate
