### ISSUE TITLE
v11.4 TypeError minifying a forEach with obj destructuring

### ISSUE THREAD

**Issue by stampycode** [coderaiser/minify#126] opened 2024-09-12 12:28 UTC
Trying to minify the following:

```js
const a = [{b:'b', c:'c'}, {b:'bb', c:'cc'}];
a.forEach(({b, c}) => {
    console.log(b, c)
})
```

causes:

```js
TypeError: @babel/template placeholder "item": Property id of VariableDeclarator expected node to be of a type ["Identifier"] but instead got "ObjectPattern"
  loc: { line: 3, column: 4 },
  rule: 'for-of/for-each'
```

**Comment by coderaiser** [comment] 2024-09-12 18:53
I cannot reproduce this, are you using latest version of **Minify**?
```js
coderaiser@localcmd:~/minify$ cat > 1.js
const a = [{b:'b', c:'c'}, {b:'bb', c:'cc'}];
a.forEach(({b, c}) => {
    console.log(b, c)
});
^C
coderaiser@localcmd:~/minify$ minify 1.js
var a=[{b:'b',c:'c'},{b:'bb',c:'cc'}];for(const{b,c} of a)log(b,c);
```

**Comment by coderaiser** [comment] 2024-09-12 20:10
I see, it is related to `BABEL_TYPES_8_BREAKING` which is enabled in bundle, but disabled in regular run, just fixed in https://github.com/babel/babel/issues/16829

**Closed** 2024-09-16 04:18 UTC
Labels: bug
